[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "book_collection_liana_vena"
version = "0.1"
authors = [{ name = "Liana Vena" }]
description = "Notion plugin for importing book data"
dependencies = ["dotenv", "requests"]
readme = "README.md"
